apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk084-my-app
  namespace: skala-practice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sk084-my-app
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8081'
        prometheus.io/path: '/actuator/prometheus'
        update: 3fa6c61089eab4bc0d5f8f447e774cf5
      labels:
        app: sk084-my-app
    spec:
      serviceAccountName: default
      containers:
      - name: my-app
        image: amdp-registry.skala-ai.com/skala25a/sk084-my-app:2.0.0-5-8d55cb10f8ab
        imagePullPolicy: Always
        env:
        - name: LOGGING_LEVEL_ROOT
          value: DEBUG
        - name: USER_NAME
          value: sk084
        - name: NAMESPACE
          value: skala-practice
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: sk000-my-app-config
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: sk000-my-app-config
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_DRIVER
          valueFrom:
            configMapKeyRef:
              name: sk000-my-app-config
              key: SPRING_DATASOURCE_DRIVER
        envFrom:
        - secretRef:
            name: sk000-my-app-secrets
            key: SPRING_DATASOURCE_PASSWORD
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness # Actuator liveness endpoint
            port: 8080 # 또는 8081 (management.server.port 설정에 따라)
          initialDelaySeconds: 60 # 컨테이너 시작 후 60초 뒤에 첫 Probe 시작
          periodSeconds: 10       # 10초마다 Probe 실행
          failureThreshold: 3     # 3번 연속 실패 시 컨테이너 재시작
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness # Actuator readiness endpoint
            port: 8080 # 또는 8081
          initialDelaySeconds: 30 # 컨테이너 시작 후 30초 뒤에 첫 Probe 시작
          periodSeconds: 10       # 10초마다 Probe 실행
          failureThreshold: 3     # 3번 연속 실패 시 Pod를 Unready 상태로 변경