spring:
  application:
    name: skala-stock-console2

  datasource:
    url: jdbc:mysql://localhost:3306/skala-stock-server-db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root # 로컬: root, 서버: skala-stock-server-user
    password: skala1234!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    defer-datasource-initialization: true
    generate-ddl: true
    open-in-view: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html