spring:
  application:
    name: skala-stock-console2

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        ddl-auto: create
    defer-datasource-initialization: true
    generate-ddl: true
    #open-in-view: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,env,beans,liveness,readiness # Add other endpoints as needed
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true # Enables liveness and readiness probes support