apiVersion: v1
kind: Service
metadata:
  name: sk084-skala-stock-console2
  namespace: skala-practice
spec:
  selector:
    app: sk084-skala-stock-console2
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: mgmt
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP


